### ISSUE TITLE
路由管理地址变成https

### ISSUE THREAD

**Issue by HSK077** [v8040/AutoBuild-OpenWrt#4]
上一个版本没有问题，请问需要关闭什么设置？
设备：OpenWrt for ARMv8_N1 v10.18.1815
固件版本：openwrt-immortalwrt-n1-ophub.img.gz
编译时间：2022.10.18 18:14
![image](https://user-images.githubusercontent.com/54111827/196404412-e9e9451b-c28b-4424-a6eb-8f1cb330c4af.png)

**Comment by v8040** [comment]
非常抱歉，最近有很大调整，建议等稳定后再下载使用

> https是因为把web服务器`uhttpd`替换成`nginx`了，有两种解决方法：

- 安装/etc/nginx/conf.d/_lan.crt 证书，浏览器就不会有提醒

- 换回uhttpd，可以使用命令：

`/etc/init.d/nginx stop`
`/etc/init.d/nginx disable`

`/etc/init.d/uhttpd enable`
`/etc/init.d/uhttpd start`

**Comment by HSK077** [comment]
问题解决，感谢回复！
